package com.mb.bee_hive.insfrastructure.database.mysql.repositories;

import com.mb.bee_hive.insfrastructure.database.mysql.models.HoneyBlend;
import com.mb.bee_hive.insfrastructure.database.repositories.IHoneyBlendRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.repository.CrudRepository;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.UUID;


/**
 * Springboot autogenerated MySQL repository
 */
public interface HoneyBlendRepository extends CrudRepository<HoneyBlend, String>, IHoneyBlendRepository {
    default void store(HoneyBlend honeyBlend){
        save(honeyBlend);
    }

    @Override
    default List<HoneyBlend> getAll() {
        ArrayList<HoneyBlend> honeyBlends = new ArrayList<HoneyBlend>();
        Iterator iterator = findAll().iterator();
        while (iterator.hasNext()) {
            HoneyBlend honeyBlend = (HoneyBlend) iterator.next();
        }
        return honeyBlends;
    }

    @Override
    default void delete(String id) {
        deleteById(id);
    }

    @Override
    default HoneyBlend getById(String id){
        return findById(id).orElse(null);
    }
}
